# Generated by Django 4.2.30 on 2026-05-08 21:39

import commandes.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeAchat',
            fields=[
                ('id_commande', models.AutoField(primary_key=True, serialize=False)),
                ('reference', models.CharField(default=commandes.models.generate_uuid8, editable=False, max_length=8, unique=True)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_PREPARATION', 'En préparation'), ('EXPEDIEE', 'Expédiée'), ('LIVREE', 'Livrée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=20)),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_ttc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('chemin_facture_pdf', models.FileField(blank=True, null=True, upload_to='factures/')),
                ('id_acheteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PanierCommande',
            fields=[
                ('id_panier', models.AutoField(primary_key=True, serialize=False)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('id_acheteur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='panier', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LignePanier',
            fields=[
                ('id_ligne', models.AutoField(primary_key=True, serialize=False)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('id_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.article')),
                ('id_panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='commandes.paniercommande')),
            ],
        ),
        migrations.CreateModel(
            name='DetailCommande',
            fields=[
                ('id_detail', models.AutoField(primary_key=True, serialize=False)),
                ('quantite_commandee', models.PositiveIntegerField()),
                ('prix_unitaire_fixe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.article')),
                ('id_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='commandes.demandeachat')),
            ],
        ),
    ]
