# Generated by Django 4.2.30 on 2026-05-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='admin_specialite',
            field=models.CharField(blank=True, choices=[('SUPER', 'Super Administrateur'), ('UTILISATEURS', 'Gestion des Utilisateurs'), ('COMMANDES', 'Gestion des Commandes'), ('PRODUITS', 'Gestion des Produits'), ('SECURITE', 'Sécurité & IDS')], default='SUPER', max_length=30, null=True),
        ),
    ]
