# Generated by Django 4.2.30 on 2026-05-08 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id_article', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantite_disponible', models.IntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('id_famille', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoArticle',
            fields=[
                ('id_photo', models.AutoField(primary_key=True, serialize=False)),
                ('chemin_fichier', models.ImageField(upload_to='articles/')),
                ('est_principale', models.BooleanField(default=False)),
                ('id_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='catalogue.article')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='id_famille',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.famille'),
        ),
        migrations.AddField(
            model_name='article',
            name='id_vendeur',
            field=models.ForeignKey(limit_choices_to={'role': 'VENDEUR'}, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
