# Generated by Django 4.2.30 on 2026-05-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoarticle',
            name='chemin_fichier',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
