# Generated by Django 4.2.30 on 2026-05-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_photo_urlfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoarticle',
            name='chemin_fichier',
            field=models.ImageField(blank=True, upload_to='produits/'),
        ),
    ]
