# Generated by Django 4.2.30 on 2026-05-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_alter_photoarticle_chemin_fichier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoarticle',
            name='chemin_fichier',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
