# Generated by Django 4.2.30 on 2026-05-08 21:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionPaiement',
            fields=[
                ('id_transaction', models.AutoField(primary_key=True, serialize=False)),
                ('reference_transaction', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('devise', models.CharField(default='MAD', max_length=3)),
                ('methode', models.CharField(choices=[('CARTE_SIMULEE', 'Carte Bancaire (Simulée)'), ('VIREMENT_SIMULE', 'Virement Bancaire (Simulé)'), ('CASH_LIVRAISON', 'Paiement à la livraison')], default='CARTE_SIMULEE', max_length=20)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours de traitement'), ('APPROUVE', 'Paiement approuvé'), ('REFUSE', 'Paiement refusé'), ('REMBOURSE', 'Remboursé')], default='EN_COURS', max_length=20)),
                ('date_transaction', models.DateTimeField(auto_now_add=True)),
                ('donnees_carte_masquees', models.CharField(blank=True, max_length=20, null=True)),
                ('id_commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_paiement', to='commandes.demandeachat')),
            ],
        ),
    ]
