# Generated by Django 4.2.30 on 2026-05-08 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlerteSecurite',
            fields=[
                ('id_alerte', models.AutoField(primary_key=True, serialize=False)),
                ('type_attaque', models.CharField(max_length=100)),
                ('niveau_severite', models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyen'), ('HIGH', 'Élevé'), ('CRITICAL', 'Critique')], default='MEDIUM', max_length=20)),
                ('ip_source', models.GenericIPAddressField()),
                ('date_detection', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('traitee', models.BooleanField(default=False)),
            ],
        ),
    ]
