# Generated by Django 4.2.30 on 2026-05-08 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alertesecurite',
            old_name='date_detection',
            new_name='horodatage',
        ),
        migrations.RemoveField(
            model_name='alertesecurite',
            name='traitee',
        ),
        migrations.AddField(
            model_name='alertesecurite',
            name='statut_alerte',
            field=models.CharField(choices=[('NOUVEAU', 'Nouveau'), ('VU', 'Vu'), ('RESOLU', 'Résolu')], default='NOUVEAU', max_length=20),
        ),
    ]
