# Generated by Django 4.2.30 on 2026-05-08 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommandationEngine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_algo', models.CharField(max_length=100)),
                ('actif', models.BooleanField(default=True)),
                ('parametres', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JournalVisite',
            fields=[
                ('id_visite', models.AutoField(primary_key=True, serialize=False)),
                ('date_consultation', models.DateTimeField(auto_now_add=True)),
                ('duree_secondes', models.IntegerField(blank=True, null=True)),
                ('id_acheteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visites', to=settings.AUTH_USER_MODEL)),
                ('id_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visites', to='catalogue.article')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreAffinite',
            fields=[
                ('id_score', models.AutoField(primary_key=True, serialize=False)),
                ('valeur_score', models.FloatField(default=0.0)),
                ('date_calcul', models.DateTimeField(auto_now=True)),
                ('id_acheteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores_affinite', to=settings.AUTH_USER_MODEL)),
                ('id_famille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores_affinite', to='catalogue.famille')),
            ],
            options={
                'unique_together': {('id_acheteur', 'id_famille')},
            },
        ),
    ]
